version: '3'

services:
  backend:
    build: ./api_sequelize
    ports:
      - 3001:3001
    environment:
      - DB_USER=
      - DB_PASS=
      - DB_NAME=
      - DB_HOST=
      - JWT_SECRET=
    volumes:
      - ./api_sequelize:/api
    container_name: clients_backend
    restart: always
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
    restart: always